# .github/workflows/generate-status-report.yml
name: Generate Status Report

on:
  schedule:
    - cron: '0 15 * * 5'  # Every Friday at 3 PM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-pptx pyyaml

      - name: Generate status report
        run: python main.py

      - name: Upload generated report
        uses: actions/upload-artifact@v3
        with:
          name: status-report
          path: status-report-*.pptx
